# Generated by Django 3.1.3 on 2020-11-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modular_name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
