# Generated by Django 3.1.3 on 2020-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headers', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=128, null=True)),
                ('payload', models.CharField(max_length=1024)),
                ('modular_id', models.IntegerField()),
            ],
        ),
    ]
