# Generated by Django 3.0.7 on 2020-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=64, null=True)),
                ('single_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_url', models.CharField(max_length=1024)),
                ('request_data', models.CharField(max_length=8192)),
                ('assert_variable', models.CharField(max_length=1024)),
                ('expect', models.CharField(max_length=1024)),
                ('is_globals', models.CharField(max_length=1024)),
                ('response_variable', models.CharField(max_length=1024)),
                ('use_variable', models.CharField(max_length=1024)),
                ('request_type', models.CharField(max_length=1024)),
                ('case_id', models.IntegerField()),
            ],
        ),
    ]
