# Generated by Django 3.0.7 on 2021-01-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_case_models_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order_where',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='result',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='response_variable',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='use_variable',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
